<?php

return [
    'template' => [
        'outbounds' => [
            [
                'type' => 'direct',
                'bind_interface' => 'eth0',
                'tag' => 'direct',
            ],
            [
                'type' => 'vless',
                'packet_encoding' => '',
                'server' => '46.29.34.167',
                'server_port' => 31634,
                'transport' => [
                    'host' => ['anten.ir'],
                    'method' => 'GET',
                    'path' => '/',
                    'type' => 'http',
                ],
                'uuid' => env('SINGBOX_EN_PROXY_UUID'),
                'domain_strategy' => 'ipv4_only',
                'tag' => ['proxy', 'en-proxy'],
            ],
            [
                'type' => 'wireguard',
                'server' => '149.40.50.112',
                'server_port' => 11640,
                'system_interface' => false,
                'local_address' => [
                    '10.69.78.245/32',
                    'fc00:bbbb:bbbb:bb01::6:4ef4/128',
                ],
                'private_key' => env('MULLVAD_WG_PRIVATE_KEY'),
                'peer_public_key' => 'wcmmadJObux2/62ES+QbIO21BkU7p2I0s6n4WNZZgW0=',
                'reserved' => [0, 0, 0],
                'workers' => 4,
                'mtu' => 1280,
                'tag' => ['proxy', 'us-proxy'],
            ],
            [
                'type' => 'wireguard',
                'server' => '95.173.222.31',
                'server_port' => 27743,
                'system_interface' => false,
                'local_address' => [
                    '10.69.78.245/32',
                    'fc00:bbbb:bbbb:bb01::6:4ef4/128',
                ],
                'private_key' => env('MULLVAD_WG_PRIVATE_KEY'),
                'peer_public_key' => 'CpbLl0WVeiW+YbJKNod5khzAI03D2hX2dhq2CCYc2Xc=',
                'reserved' => [0, 0, 0],
                'workers' => 4,
                'mtu' => 1280,
                'tag' => ['proxy', 'fr-proxy'],
            ],
        ],
        'route' => [
            'final' => env('SINGBOX_FINAL', 'direct'),
            'default_interface' => 'eth0',
            'auto_detect_interface' => false,
            'rule_set' => [
                ['format' => 'binary', 'type' => 'local', 'path' => 'sing-geosite/geosite-category-ir.srs', 'tag' => 'geosite:category-ir'],
                ['format' => 'binary', 'type' => 'local', 'path' => 'sing-geosite/geosite-category-ru.srs', 'tag' => 'geosite:category-ru'],
                ['format' => 'binary', 'type' => 'local', 'path' => 'sing-geosite/geosite-cn.srs', 'tag' => 'geosite:category-cn'],
                ['format' => 'binary', 'type' => 'local', 'path' => 'sing-geosite/geosite-category-ads-all.srs', 'tag' => 'geosite:category-ads-all'],
                ['format' => 'binary', 'type' => 'local', 'path' => 'sing-geosite/geosite-github.srs', 'tag' => 'geosite:github'],
                ['format' => 'binary', 'type' => 'local', 'path' => 'sing-geoip/geoip-ir.srs', 'tag' => 'geoip:ir'],
                ['format' => 'binary', 'type' => 'local', 'path' => 'sing-geoip/geoip-cn.srs', 'tag' => 'geoip:cn'],
                ['format' => 'binary', 'type' => 'local', 'path' => 'sing-geoip/geoip-ru.srs', 'tag' => 'geoip:ru'],
                ['format' => 'binary', 'path' => 'sing-geosite/geosite-telegram.srs', 'tag' => 'geosite:telegram', 'type' => 'local'],
                ['format' => 'binary', 'path' => 'sing-geosite/geosite-discord.srs', 'tag' => 'geosite:discord', 'type' => 'local'],
                ['format' => 'binary', 'path' => 'sing-geosite/geosite-category-porn.srs', 'tag' => 'geosite:category-porn', 'type' => 'local'],
                ['format' => 'binary', 'path' => 'sing-geosite/geosite-spotify.srs', 'tag' => 'geosite:spotify', 'type' => 'local'],
                ['format' => 'binary', 'path' => 'sing-geosite/geosite-android.srs', 'tag' => 'geosite:android', 'type' => 'local'],
                ['format' => 'binary', 'path' => 'sing-geosite/geosite-youtube.srs', 'tag' => 'geosite:youtube', 'type' => 'local'],
                ['format' => 'binary', 'path' => 'sing-geosite/geosite-x.srs', 'tag' => 'geosite:x', 'type' => 'local'],
                ['format' => 'binary', 'path' => 'sing-geosite/geosite-twitter.srs', 'tag' => 'geosite:twitter', 'type' => 'local'],
                ['format' => 'binary', 'path' => 'sing-geosite/geosite-instagram.srs', 'tag' => 'geosite:instagram', 'type' => 'local'],
                ['format' => 'binary', 'path' => 'sing-geosite/geosite-cloudflare.srs', 'tag' => 'geosite:cloudflare', 'type' => 'local'],
                ['format' => 'binary', 'path' => 'sing-geosite/geosite-docker.srs', 'tag' => 'geosite:docker', 'type' => 'local'],
                ['format' => 'binary', 'path' => 'sing-geosite/geosite-facebook.srs', 'tag' => 'geosite:facebook', 'type' => 'local'],
                ['format' => 'binary', 'path' => 'sing-geosite/geosite-category-communication.srs', 'tag' => 'geosite:category-communication', 'type' => 'local'],
                ['format' => 'binary', 'path' => 'sing-geosite/geosite-category-entertainment.srs', 'tag' => 'geosite:category-entertainment', 'type' => 'local'],
                ['format' => 'binary', 'path' => 'sing-geosite/geosite-category-media.srs', 'tag' => 'geosite:category-media', 'type' => 'local'],
                ['format' => 'binary', 'path' => 'sing-geosite/geosite-openai.srs', 'tag' => 'geosite:openai', 'type' => 'local'],
                ['format' => 'binary', 'path' => 'sing-geosite/geosite-zoom.srs', 'tag' => 'geosite:zoom', 'type' => 'local'],
                ['format' => 'binary', 'path' => 'sing-geosite/geosite-google.srs', 'tag' => 'geosite:google', 'type' => 'local'],
                ['format' => 'binary', 'path' => 'sing-geosite/geosite-stackexchange.srs', 'tag' => 'geosite:stackexchange', 'type' => 'local'],
                ['format' => 'binary', 'path' => 'custom/geoip-bunny.srs', 'tag' => 'geoip:bunny', 'type' => 'local'],
                ['format' => 'binary', 'path' => 'sing-geosite/geosite-sourceforge.srs', 'tag' => 'geosite:sourceforge', 'type' => 'local'],
                ['format' => 'binary', 'path' => 'sing-geosite/geosite-category-anticensorship.srs', 'tag' => 'geosite:category-anticensorship', 'type' => 'local'],
                ['format' => 'binary', 'path' => 'sing-geosite/geosite-figma.srs', 'tag' => 'geosite:figma', 'type' => 'local'],
                ['format' => 'binary', 'path' => 'sing-geosite/geosite-category-dev.srs', 'tag' => 'geosite:category-dev', 'type' => 'local'],
                ['format' => 'binary', 'type' => 'local', 'path' => 'Iran-sing-box-rules/geoip-telegram.srs', 'tag' => 'geoip:telegram'],
                ['format' => 'binary', 'type' => 'local', 'path' => 'Iran-sing-box-rules/geoip-facebook.srs', 'tag' => 'geoip:facebook'],
                ['format' => 'binary', 'type' => 'local', 'path' => 'Iran-sing-box-rules/geoip-twitter.srs', 'tag' => 'geoip:twitter'],
                ['format' => 'binary', 'type' => 'local', 'path' => 'Iran-sing-box-rules/geoip-google.srs', 'tag' => 'geoip:google'],
                ['format' => 'binary', 'type' => 'local', 'path' => 'Iran-sing-box-rules/geoip-oracle.srs', 'tag' => 'geoip:oracle'],
                ['format' => 'binary', 'type' => 'local', 'path' => 'Iran-sing-box-rules/geoip-cloudflare.srs', 'tag' => 'geoip:cloudflare'],
                ['format' => 'binary', 'type' => 'local', 'path' => 'Iran-sing-box-rules/geoip-private.srs', 'tag' => 'geoip:private'],
                ['format' => 'binary', 'type' => 'local', 'path' => 'Iran-sing-box-rules/geosite-oracle.srs', 'tag' => 'geosite:oracle'],
                ['format' => 'binary', 'type' => 'local', 'path' => 'custom/geosite-postman.srs', 'tag' => 'geosite:postman'],
                ['format' => 'binary', 'type' => 'local', 'path' => 'custom/geosite-google-direct.srs', 'tag' => 'geosite:google-direct'],
            ],
            'rules' => [
                ['action' => 'sniff'],
                ['ip_cidr' => ['224.0.0.0/3', 'ff00::/8'], 'source_ip_cidr' => ['224.0.0.0/3', 'ff00::/8'], 'action' => 'reject'],
                ['protocol' => 'dns', 'action' => 'hijack-dns'],
                [
                    'simple_rules' => [
                        'geosite:category-ads-all' => 'block',
                        'geosite:telegram' => 'proxy',
                        'geosite:discord' => 'proxy',
                        'geosite:android' => 'proxy',
                        'geosite:youtube' => 'proxy',
                        'geosite:category-ir' => 'direct',
                        'geosite:category-ru' => 'direct',
                        'geosite:category-cn' => 'direct',
                        'geosite:google-direct' => 'direct',
                        'geosite:spotify' => 'fr-proxy',
                        'geosite:google' => 'fr-proxy',
                        'geosite:category-porn' => 'us-proxy',
                        'geosite:x' => 'us-proxy',
                        'geosite:twitter' => 'us-proxy',
                        'geoip:twitter' => 'us-proxy',
                        'geoip:telegram' => 'proxy',
                        'domain_suffix:cloudflare-dns.com' => 'proxy',
                        'domain_suffix:unibet.co.uk' => 'proxy',
                        'domain_suffix:pokernow.club' => 'proxy',
                        'domain_suffix:dockerstatic.com' => 'proxy',
                        'domain_suffix:lenovo.com' => 'proxy',
                        'domain_suffix:usefanthom.com' => 'proxy',
                        'domain_suffix:api.github.com' => 'proxy',
                        'domain_suffix:marketplace.visualstudio.com' => 'proxy',
                        'domain_suffix:copilot-telemetry.githubusercontent.com' => 'proxy',
                        'domain_suffix:githubcopilot.com' => 'proxy',
                        'domain_suffix:bunny.net' => 'proxy',
                        'domain_suffix:signnow.com' => 'proxy',
                        'domain_suffix:ntp.org' => 'direct',
                        'domain_suffix:configserver.pro' => 'direct',
                        'domain_suffix:hesabfa.com' => 'direct',
                        'geoip:ir' => 'direct',
                        'geoip:cn' => 'direct',
                        'geoip:ru' => 'direct',
                        'geoip:private' => 'direct',
                        'geoip:cloudflare' => 'proxy',
                        'geoip:facebook' => 'proxy',
                        'geoip:oracle' => 'proxy',
                        'domain_suffix:laravel.com' => 'proxy',
                        'domain_suffix:usefathom.com' => 'proxy',
                        'domain_suffix:jam.dev' => 'proxy',
                        'domain_suffix:packages.microsoft.com' => 'proxy',
                        'domain_suffix:cafearz.com' => 'proxy',
                        'domain_suffix:cafearz.net' => 'proxy',
                        'domain_suffix:unpkg.com' => 'proxy',
                        'domain_suffix:mullvad.net' => 'proxy',
                        'domain_suffix:dns.google' => 'proxy',
                        'domain_suffix:zarfilm.com' => 'proxy',
                        'geosite:cloudflare' => 'proxy',
                        'geosite:instagram' => 'proxy',
                        'geosite:facebook' => 'proxy',
                        'geosite:oracle' => 'proxy',
                        'geosite:postman' => 'proxy',
                        'geosite:figma' => 'proxy',
                        'geosite:docker' => 'proxy',
                        'geosite:category-communication' => 'proxy',
                        'geosite:category-entertainment' => 'proxy',
                        'geosite:category-media' => 'proxy',
                        'geosite:openai' => 'proxy',
                        'geosite:zoom' => 'proxy',
                        'geosite:sourceforge' => 'proxy',
                        'geosite:category-anticensorship' => 'proxy',
                        'geosite:category-dev' => 'proxy',
                    ],
                ],
            ],
        ],
        'dns' => [
            'rules' => [
                ['simple_rules' => 'auto'],
            ],
        ],
        'inbounds' => [
            [
                'type' => 'direct',
                'listen' => '0.0.0.0',
                'listen_port' => 53,
            ],
            [
                'address' => [
                    '172.31.255.252/30',
                ],
                'route_exclude_address' => [
                    '193.138.7.132/32',
                    '193.32.126.81/32',
                    '193.32.126.82/32',
                    '146.70.184.194/32',
                    '146.70.184.130/32',
                ],
                'stack' => 'system',
                'tag' => 'tun-in',
                'type' => 'tun',
                'auto_route' => true,
                'strict_route' => true,
                'auto_redirect' => true,
                'interface_name' => 'sing-br',
            ],
            [
                'listen_port' => 1080,
                'type' => 'mixed',
                'listen' => '0.0.0.0',
                'tag' => 'mixed-in',
            ],
        ],
        'experimental' => [
            'clash_api' => [
                'external_controller' => '0.0.0.0:9090',
                'external_ui' => 'ui',
                'access_control_allow_origin' => [
                    'http://127.0.0.1',
                    'http://192.168.1.254',
                    'https://yacd.haishan.me',
                ],
                'access_control_allow_private_network' => true,
            ],
        ],
    ],
];
